### ISSUE TITLE
when i try to run this i get " php artisan starter:insert-demo-data --fresh"

### ISSUE THREAD

**Issue by techliferestore** [nasirkhan/laravel-starter#375] opened 2022-12-06 06:39 UTC
ErrorException 

  Attempt to read property "name" on null

  at Modules/Article/Entities/Post.php:76
     72▕     {
     73▕         $this->attributes['created_by_name'] = trim(label_case($value));
     74▕ 
     75▕         if (empty($value)) {
  ➜  76▕             $this->attributes['created_by_name'] = auth()->user()->name;
     77▕         }
     78▕     }
     79▕ 
     80▕     /**

  1   Modules/Article/Entities/Post.php:76
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}()

      +9 vendor frames 
  11  [internal]:0
      Illuminate\Database\Eloquent\Factories\Factory::Illuminate\Database\Eloquent\Factories\{closure}()

**Comment by nasirkhan** [comment] 2022-12-06 11:45
can you please write a little more details about the error? like on which page you got this error?

**Comment by nasirkhan** [comment] 2022-12-08 15:38
possible duplicate of #374

**Closed as completed by nasirkhan** 2022-12-08 15:38 UTC
